TESTS = bubblesort_byte\
        bubblesort_hword\
        bubblesort_word\
        int_euclid\
        int_divide\
        int_sqrt\
        int_minmax

all: $(TESTS)

$(TESTS):
	sh ../run.sh $@
#	sh ../run-toolchain.sh $@
