#
# ISP RAS (http://www.ispras.ru)
#
# This ruby template was automatically generated by the MicroTESK tool
# Generation started: Wed Feb 06 16:57:26 MSK 2019
#

require_relative '../riscv_base'

class SimpleGenTemplate < RiscVBaseTemplate
  def pre
    super
    data {
      label :data
      word rand(1, 9), rand(1, 9), rand(1, 9), rand(1, 9)
      label :end_data
      space 1
    }
  end
  
  def run
    if is_rev('RV32F') then    
    la x(5), :data
    flw f(_), x(5), :data
    
    la x(5), :data
    fsw f(5), x(5), :data
    
    fadd_s f(_), f(_), f(_)
    
    fsub_s f(_), f(_), f(_)
    
    fmul_s f(_), f(_), f(_)
    
    fdiv_s f(_), f(_), f(_)
    
    fmin_s f(_), f(_), f(_)
    
    fmax_s f(_), f(_), f(_)
    
    fsqrt_s f(_), f(_)
    
    fsgnj_s f(_), f(_), f(_)
    
    fsgnjn_s f(_), f(_), f(_)
    
    fsgnjx_s f(_), f(_), f(_)
    
    fmadd_s f(_), f(_), f(_), f(_)
    
    fmsub_s f(_), f(_), f(_), f(_)
    
    fnmadd_s f(_), f(_), f(_), f(_)
    
    fnmsub_s f(_), f(_), f(_), f(_)
    
    fcvt_w_s x(_), f(_), _
    
    fcvt_w_s2 x(_), f(_)
    
    fcvt_wu_s x(_), f(_), _
    
    fcvt_wu_s2 x(_), f(_)
    
    fcvt_s_w f(_), x(_)
    
    fcvt_s_wu f(_), x(_)
    
    fmv_x_w x(_), f(_)
    
    fmv_w_x f(_), x(_)
    
    feq_s x(_), f(_), f(_)
    
    flt_s x(_), f(_), f(_)
    
    fle_s x(_), f(_), f(_)
    
    fclass_s x(_), f(_)
    
    fmv_s f(_), f(_)
    
    fabs_s f(_), f(_)
    
    fneg_s f(_), f(_)
    
    fmv_x_s x(_), f(_)
    
    fmv_s_x f(_), x(_)
    end

    if is_rev('RV32D') then    
    la x(5), :data
    fld f(_), x(5), :data
    
    la x(5), :data
    fsd f(5), x(5), :data
    
    fadd_d f(_), f(_), f(_)
    
    fsub_d f(_), f(_), f(_)
    
    fmul_d f(_), f(_), f(_)
    
    fdiv_d f(_), f(_), f(_)
    
    fmin_d f(_), f(_), f(_)
    
    fmax_d f(_), f(_), f(_)
    
    fsqrt_d f(_), f(_)
    
    fsgnj_d f(_), f(_), f(_)
    
    fsgnjn_d f(_), f(_), f(_)
    
    fsgnjx_d f(_), f(_), f(_)
    
    fmadd_d f(_), f(_), f(_), f(_)
    
    fmsub_d f(_), f(_), f(_), f(_)
    
    fnmadd_d f(_), f(_), f(_), f(_)
    
    fnmsub_d f(_), f(_), f(_), f(_)
    
    fcvt_w_d x(_), f(_), _
    
    fcvt_w_d2 x(_), f(_)
    
    fcvt_wu_d x(_), f(_), _
    
    fcvt_wu_d2 x(_), f(_)
    
    fcvt_d_w f(_), x(_)
    
    fcvt_d_wu f(_), x(_)
    
    fcvt_s_d f(_), f(_)
    
    fcvt_d_s f(_), f(_)
    
    feq_d x(_), f(_), f(_)
    
    flt_d x(_), f(_), f(_)
    
    fle_d x(_), f(_), f(_)
    
    fclass_d x(_), f(_)
    
    fmv_d f(_), f(_)
    
    fabs_d f(_), f(_)
    
    fneg_d f(_), f(_)
     
    la x(5), :data
    lwu x(_), x(5), :data
    
    la x(5), :data
    ld x(_), x(5), :data
    
    la x(5), :data
    sd x(5), x(5), :data
    end
    
    if is_rev('RV64I') then
    addiw x(_), x(_), _
    
    slliw x(_), x(_), _
    
    srliw x(_), x(_), _
    
    sraiw x(_), x(_), _
    
    addw x(_), x(_), x(_)
    
    subw x(_), x(_), x(_)
    
    sllw x(_), x(_), x(_)
    
    srlw x(_), x(_), x(_)
    
    sraw x(_), x(_), x(_)
    end

    lui x(_), _
    
    auipc x(_), _
    
    la x(3), :jal_label
    jal x(3), :jal_label
    nop
    label :jal_label
    nop
    
    beq x(_), x(_), :beq_label
    nop
    label :beq_label
    nop
    
    bne x(_), x(_), :bne_label
    nop
    label :bne_label
    nop
    
    blt x(_), x(_), :blt_label
    nop
    label :blt_label
    nop
    
    bltu x(_), x(_), :bltu_label
    nop
    label :bltu_label
    nop
    
    bge x(_), x(_), :bge_label
    nop
    label :bge_label
    nop
    
    bgeu x(_), x(_), :bgeu_label
    nop
    label :bgeu_label
    nop
    
    la x(5), :data
    lw x(_), x(5), :data
    
    la x(5), :data
    lh x(_), x(5), :data
    
    la x(5), :data
    lhu x(_), x(5), :data
    
    la x(5), :data
    lb x(_), x(5), :data
    
    la x(5), :data
    lbu x(_), x(5), :data
    
    la x(5), :data
    sw x(5), x(5), :data
    
    la x(5), :data
    sh x(5), x(5), :data
    
    la x(5), :data
    sb x(5), x(5), :data
    
    addi x(_), x(_), _
    
    slti x(_), x(_), _
    
    sltiu x(_), x(_), _
    
    xori x(_), x(_), _
    
    ori x(_), x(_), _
    
    andi x(_), x(_), _
    
    slli x(_), x(_), _
    
    srli x(_), x(_), _
    
    srai x(_), x(_), _
    
    sll x(_), x(_), x(_)
    
    srl x(_), x(_), x(_)
    
    sra x(_), x(_), x(_)
    
    add x(_), x(_), x(_)
    
    sub x(_), x(_), x(_)
    
    slt x(_), x(_), x(_)
    
    sltu x(_), x(_), x(_)
    
    AND x(_), x(_), x(_)
    
    OR x(_), x(_), x(_)
    
    xor x(_), x(_), x(_)
    
    nop 
    
    mv x(_), x(_)
    
    NOT x(_), x(_)
    
    neg x(_), x(_)
    
    seqz x(_), x(_)
    
    snez x(_), x(_)
    
    sltz x(_), x(_)
    
    sgtz x(_), x(_)
    
    la x(3), :j_label
    j :j_label
    nop
    label :j_label
    nop
    
    la x(3), :jr_label
    jr x(3)
    nop
    label :jr_label
    nop
    
    beqz x(_), :beqz_label
    nop
    label :beqz_label
    nop
    
    bnez x(_), :bnez_label
    nop
    label :bnez_label
    nop
    
    blez x(_), :blez_label
    nop
    label :blez_label
    nop
    
    bgez x(_), :bgez_label
    nop
    label :bgez_label
    nop
    
    bltz x(_), :bltz_label
    nop
    label :bltz_label
    nop
    
    bgtz x(_), :bgtz_label
    nop
    label :bgtz_label
    nop

    if is_rev('RV32V') then
    vadd vr(_), vr(_), vr(_)
    
    vsub vr(_), vr(_), vr(_)
    
    vsl vr(_), vr(_), vr(_)
    
    vsr vr(_), vr(_), vr(_)
    
    vand vr(_), vr(_), vr(_)
    
    vor vr(_), vr(_), vr(_)
    
    vxor vr(_), vr(_), vr(_)
    
    vseq vr(_), vr(_), vr(_)
    
    vsne vr(_), vr(_), vr(_)
    
    vslt vr(_), vr(_), vr(_)
    
    vsge vr(_), vr(_), vr(_)
    
    vclip vr(_), vr(_), x(_)
    
    vcvt vr(_), vr(_), x(_)
    
    vmpop x(_), vr(_)
    
    vmfirst x(_), vr(_)
    
    vextract x(_), vr(_), x(_)
    
    vinsert vr(_), x(_), x(_)
    
    vmerge vr(_), vr(_), vr(_)
    
    vselect vr(_), vr(_), vr(_)
    
    vslide vr(_), vr(_), x(_)
    
    vdiv vr(_), vr(_), vr(_)
    
    vrem vr(_), vr(_), vr(_)
    
    vmul vr(_), vr(_), vr(_)
    
    vmulh vr(_), vr(_), vr(_)
    
    vmin vr(_), vr(_), vr(_)
    
    vmax vr(_), vr(_), vr(_)
    
    vsgnj vr(_), vr(_), vr(_)
    
    vsgnjn vr(_), vr(_), vr(_)
    
    vsgnjx vr(_), vr(_), vr(_)
    
    vsqrt vr(_), vr(_)
    
    vclass vr(_), vr(_)
    
    vpopc vr(_), vr(_)
    
    vaddi vr(_), vr(_), _
    
    vsli vr(_), vr(_), _
    
    vsri vr(_), vr(_), _
    
    vandi vr(_), vr(_), _
    
    vori vr(_), vr(_), _
    
    vxori vr(_), vr(_), _
    
    vclipi vr(_), vr(_), _
    
    vmadd vr(_), vr(_), vr(_), vr(_)
    
    vmsub vr(_), vr(_), vr(_), vr(_)
    
    vnmadd vr(_), vr(_), vr(_), vr(_)
    
    vnmsub vr(_), vr(_), vr(_), vr(_)
    
    vld vr(_), x(_), _
    
    vlds vr(_), x(_), x(_), _
    
    vldx vr(_), x(_), vr(_), _
    
    vst x(_), vr(_), _
    
    vsts x(_), x(_), vr(_), _
    
    vstx x(_), vr(_), vr(_), _
    
    vamoswap vr(_), vr(_), vr(_)
    
    vamoadd vr(_), vr(_), vr(_)
    
    vamoand vr(_), vr(_), vr(_)
    
    vamoor vr(_), vr(_), vr(_)
    
    vamoxor vr(_), vr(_), vr(_)
    
    vamomin vr(_), vr(_), vr(_)
    
    vamomax vr(_), vr(_), vr(_)
    
    fcvt_l_d x(_), f(_), _
    
    fcvt_l_d2 x(_), f(_)
    
    fcvt_lu_d x(_), f(_), _
    
    fcvt_lu_d2 x(_), f(_)
    
    fcvt_d_l f(_), x(_)
    
    fcvt_d_lu f(_), x(_)
    
    fmv_x_d x(_), f(_)
    
    fmv_d_x f(_), x(_)
    
    fcvt_l_s x(_), f(_), _
    
    fcvt_l_s2 x(_), f(_)
    
    fcvt_lu_s x(_), f(_), _
    
    fcvt_lu_s2 x(_), f(_)
    
    fcvt_s_l f(_), x(_)
    
    fcvt_s_lu f(_), x(_)
  
    la x(5), :data
    lr_d x(_), x(5)
    
    la x(5), :data
    sc_d x(_), x(5), x(5)
    end
    
    if is_rev('RV32A') then
    la x(5), :data
    amoswap_d x(_), x(5), x(5)
    
    la x(5), :data
    amoadd_d x(_), x(5), x(5)
    
    la x(5), :data
    amoand_d x(_), x(5), x(5)
    
    la x(5), :data
    amoor_d x(_), x(5), x(5)
    
    la x(5), :data
    amoxor_d x(_), x(5), x(5)
    
    la x(5), :data
    amomin_d x(_), x(5), x(5)
    
    la x(5), :data
    amomax_d x(_), x(5), x(5)
    
    la x(5), :data
    amominu_d x(_), x(5), x(5)
    
    la x(5), :data
    amomaxu_d x(_), x(5), x(5)
    end

    if is_rev('RV64M') then
    mulw x(_), x(_), x(_)
    
    divw x(_), x(_), x(_)
    
    divuw x(_), x(_), x(_)
    
    remw x(_), x(_), x(_)
    
    remuw x(_), x(_), x(_)
    
    la x(5), :data
    lr_w x(_), x(5)
    
    la x(5), :data
    sc_w x(_), x(5), x(5)
    end
    
    if is_rev('RV64A') then
    la x(5), :data
    amoswap_w x(_), x(5), x(5)
    
    la x(5), :data
    amoadd_w x(_), x(5), x(5)
    
    la x(5), :data
    amoand_w x(_), x(5), x(5)
    
    la x(5), :data
    amoor_w x(_), x(5), x(5)
    
    la x(5), :data
    amoxor_w x(_), x(5), x(5)
    
    la x(5), :data
    amomin_w x(_), x(5), x(5)
    
    la x(5), :data
    amomax_w x(_), x(5), x(5)
    
    la x(5), :data
    amominu_w x(_), x(5), x(5)
    
    la x(5), :data
    amomaxu_w x(_), x(5), x(5)
    end

    mul x(_), x(_), x(_)
    
    mulh x(_), x(_), x(_)
    
    mulhu x(_), x(_), x(_)
    
    mulhsu x(_), x(_), x(_)
    
    div x(_), x(_), x(_)
    
    divu x(_), x(_), x(_)
    
    rem x(_), x(_), x(_)
    
    remu x(_), x(_), x(_)
    
    fence_i 
    
    csrrw x(_), ustatus(), x(_)
    
    csrrs x(_), ustatus(), x(_)
    
    csrrc x(_), ustatus(), x(_)
    
    csrrwi x(_), ustatus(), _
    
    csrrsi x(_), ustatus(), _
    
    csrrci x(_), ustatus(), _
    
    csrw ustatus(), x(_)
    
    csrr x(_), ustatus()
    
    csrs ustatus(), x(_)
    
    csrc ustatus(), x(_)
    
    csrwi ustatus(), _
    
    csrsi ustatus(), _
    
    csrci ustatus(), _
    
    frcsr x(_)
    
    fscsr x(_), x(_)
    
    fscsr2 x(_)
    
    frrm x(_)
    
    fsrm x(_), x(_)
    
    fsrm2 x(_)
    
    fsrmi x(_), _
    
    fsrmi2 _
    
    frflags x(_)
    
    fsflags x(_), x(_)
    
    fsflags2 x(_)
    
    fsflagsi x(_), _
    
    fsflagsi2 _
    
    rdinstret x(_)
    
    rdcycle x(_)
    
    rdtime x(_)
  end
end
