all:
	make -C euclid
	make -C fibonacci
	make -C idiv
	make -C memset
	make -C strlen
	make -C sum

clean:
	make clean -C euclid
	make clean -C fibonacci
	make clean -C idiv
	make clean -C memset
	make clean -C strlen
	make clean -C sum
