all:
	make -C rv32uc
	make -C rv32ui
	make -C rv32um
# NOT SUPPORTED IN SCR1
#	make -C rv32ud
#	make -C rv32uf
#	make -C rv32ua
#	make -C rv64mi
#	make -C rv64si
#	make -C rv64ua
#	make -C rv64uc
#	make -C rv64ud
#	make -C rv64uf
#	make -C rv64ui
#	make -C rv64um
